import{a as f,S as h,i as c}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y="44474064-e47939977861edfa0fa12c2ac",g="https://pixabay.com/api/";async function d(n,o=1){const s=await f.get(g,{params:{key:y,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}});if(s.status!==200)throw new Error("Failed to fetch images");return s.data}const p=new h(".gallery a");function u(n){const o=document.querySelector(".gallery"),s=n.map(({webformatURL:a,largeImageURL:e,tags:t,likes:i,views:r,comments:l,downloads:m})=>`
      <a class="gallery__item" href="${e}">
        <img class="gallery__image" src="${a}" width=360; height=200; alt="${t}" />
        <div class="info">
          <p>Likes: ${i}</p>
          <p>Views: ${r}</p>
          <p>Comments: ${l}</p>
          <p>Downloads: ${m}</p>
        </div>
      </a>
    `).join("");o.insertAdjacentHTML("beforeend",s),p.refresh()}document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector("#search-form"),o=document.querySelector(".gallery"),s=document.querySelector(".load-more"),a=document.querySelector(".loader");let e=1,t="";function i(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}n.addEventListener("submit",async r=>{if(r.preventDefault(),t=r.currentTarget.elements.query.value.trim(),!t){c.error({title:"Error",message:"Please enter a search query!"});return}o.innerHTML="",e=1,s.classList.add("hidden"),a.classList.add("visible");try{const l=await d(t,e);l.hits.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(u(l.hits),s.classList.remove("hidden"))}catch(l){c.error({title:"Error",message:l.message})}finally{a.classList.remove("visible")}}),s.addEventListener("click",async()=>{e+=1,a.classList.add("visible");try{const r=await d(t,e);u(r.hits),i(),(r.hits.length===0||e*12>=r.totalHits)&&(s.classList.add("hidden"),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(r){c.error({title:"Error",message:r.message})}finally{a.classList.remove("visible")}})});
//# sourceMappingURL=commonHelpers.js.map
